/* Generated By:JavaCC: Do not edit this line. GDLConstants.java */
package tk.exgerm.persistance.parser.GDLParser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface GDLConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int GRAPH = 10;
  /** RegularExpression Id. */
  int NODE = 11;
  /** RegularExpression Id. */
  int EDGE = 12;
  /** RegularExpression Id. */
  int ID = 13;
  /** RegularExpression Id. */
  int HEX_DIGIT = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int DIGIT = 16;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 17;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 18;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 19;
  /** RegularExpression Id. */
  int STRING_LITERAL = 20;
  /** RegularExpression Id. */
  int UNDIRECTED = 21;
  /** RegularExpression Id. */
  int RIGHT = 22;
  /** RegularExpression Id. */
  int LEFT = 23;
  /** RegularExpression Id. */
  int LBRACE = 24;
  /** RegularExpression Id. */
  int RBRACE = 25;
  /** RegularExpression Id. */
  int LBRACKET = 26;
  /** RegularExpression Id. */
  int RBRACKET = 27;
  /** RegularExpression Id. */
  int SEMICOLON = 28;
  /** RegularExpression Id. */
  int EQ = 29;
  /** RegularExpression Id. */
  int COMMA = 30;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"/*\"",
    "<token of kind 2>",
    "\"*/\"",
    "<token of kind 4>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"graph\"",
    "\"node\"",
    "\"edge\"",
    "<ID>",
    "<HEX_DIGIT>",
    "<LETTER>",
    "<DIGIT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<STRING_LITERAL>",
    "\"--\"",
    "\"->\"",
    "\"<-\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"=\"",
    "\",\"",
  };

}
